---
title: "Coffee Ratings TT"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, message = FALSE}
library(tidyverse)
coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')
coffee_ratings %>% glimpse

```


```{r}
coffee_ratings %>% ggplot(aes(total_cup_points)) + geom_histogram() + scale_x_log10()
```

```{r}
### Owners can own multiple companes, composed of multiple farms
### some are individually owned.
coffee_ratings %>%
  select(owner,company, farm_name) %>%
  count(company, farm_name, sort = T) %>%
  drop_na()

```




```{r}
## There are farms with multiple owners.

coffee_ratings %>% 
  count(farm_name, owner) %>%
  drop_na() %>%
  arrange(farm_name) %>%
  count(farm_name, sort = T)
```

```{r}

# verify that we captured all predictors for total_cup_points value

coffee_ratings %>%
  select(total_cup_points,country_of_origin, aroma:cupper_points) %>%
  mutate(row_num = row_number()) %>%
  gather(key = "key", value = "value", -total_cup_points, -country_of_origin, -row_num) %>%
  group_by(row_num) %>%
  summarise(value = sum(value), total_cup_points = mean(total_cup_points))

```

```{r}

coffee_ratings %>%
  filter(country_of_origin == "Ethiopia") %>%
  select(aroma:cupper_points) %>%
  gather() %>%
  group_by(key) %>%
  summarise(value = mean(value)) %>%
  ungroup() %>%
  mutate(key = str_replace(key, "_", " ") %>% str_to_title()) %>%
  mutate(key = fct_reorder(key, value)) %>%
  ggplot(aes(x = key, y = value, color = key)) + 
  geom_point(size = 5) +
  geom_segment(aes(x = key, xend = key, y = value, yend = 0)) +
  theme(legend.position = "none") + 
  ylab("") +
  xlab(NULL) + 
  coord_flip() +
  labs(title = "Average Point Rating")


```


```{r}

coffee_ratings %>%
  filter(country_of_origin == "Ethiopia") %>%
  select(variety) %>%
  drop_na() %>%
  count(variety) %>%
  mutate(variety = fct_reorder(variety, n)) %>%
  ggplot(aes(x = n, y = variety, fill = variety)) +
  geom_col() + 
  ylab(NULL) +
  labs(title = " Bean Variety") +
  theme(legend.position = "none")
```


```{r}
library(kableExtra)
coffee_ratings %>%
  filter(country_of_origin == "Ethiopia") %>%
  select(total_cup_points, country_of_origin, region, species) %>%
  group_by(species, region) %>%
  top_n(total_cup_points, n = 1) %>%
  ungroup() %>%
  mutate(region = str_trunc(region, 12, "right")) %>%
  arrange(desc(total_cup_points)) %>%
  kable()
```



```{r}
library(broom)
coffee_ratings %>%
  select(country_of_origin, aroma:cupper_points) %>%
  mutate(highlight = if_else(country_of_origin == "Ethiopia", "Highlight", "No-Highlight")) %>%
  select(-country_of_origin) %>%
  gather(key = "key", value = "value", -highlight) %>%
  group_by(key) %>%
  do(t_test = t.test(value~highlight, data = .) %>% tidy()) %>%
  unnest(t_test) %>%
  mutate(difference = case_when(
         conf.low <0 & conf.high < 0 ~ "Different",
         conf.low > 0 & conf.high >0 ~ "Different",
         TRUE ~ "Not-Different")) %>%
  mutate(key = str_replace(key, "_", " ") %>% str_to_title()) %>%
  mutate(key = fct_reorder(key, estimate)) %>%
  ggplot(aes(x = key, y = estimate, color = difference)) + 
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme(legend.position = "none") +
  xlab(NULL) +
  labs(title = "How does Ethiopian Coffee Compare?")

```

